---
language: java
dist: jammy

jdk:
- openjdk11

notifications:
  email: true

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

stages:
  - name: Build-Test

before_install:
  - sudo apt-get update
  - env | grep TRAVIS
  - pyenv global 3.8

jobs:
  include:
    - stage: Build-Test
      jdk: openjdk11
      install: true
      script:
        - build/setMavenVersion.sh
        - mvn verify -fae -DskipITs $MVN_ARGS

    - jdk: openjdk17
      install: true
      script:
        - mvn verify -fae -DskipITs $MVN_ARGS